fix: Rename 'range' to 'vol_range' - reserved keyword error
Error: "range" cannot be used as a variable name in Pine Script
Fixed: Changed to 'vol_range' in dynamic TP calculation